volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:

configs:
  qdrant_config:
    content: |
      log_level: INFO  
      enable_tls: false  # Set to true if using HTTPS
      service:
        http_port: ${QDRANT_PORT}
      storage:
        storage_path: "/qdrant/storage"

services:

  neo4j:
    image: neo4j:5.26.2-ubi9
    container_name: neo4j
    restart: unless-stopped
    ports:
      - ${NEO4J_GUI_PORT}:${NEO4J_GUI_PORT}
      - ${NEO4J_PORT}:${NEO4J_PORT}
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS='["apoc"]'
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted="apoc.*"
    volumes:
      - ../help/neo4j/import:/var/lib/neo4j/import
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins

  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: qdrant
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - ${QDRANT_PORT}:${QDRANT_PORT}
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ../help/qdrant/storage:/qdrant/storage